sudo: required
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
        pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl;
      elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
        pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl;
    fi
  - pip3 install torchvision

script:
  - python3 -m test --no-cuda
  - python3 -m main --model "cnn_7" --no-cuda --ci
  - python3 -m main --model "capsule" --no-cuda --ci
  - python3 -m main --model "resnet_18" --no-cuda --ci
  - python3 -m main --model "squeezenet_v10" --no-cuda --ci
